# Generated by Django 3.0.1 on 2020-06-13 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cemetery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('cemetery_type', models.CharField(choices=[('Conservation cemetery', 'Conservation cemetery'), ('Natural cemetery', 'Natural cemetery'), ('Hybrid cemetery', 'Hybrid cemetery')], default='Conservation cemetery', max_length=21)),
            ],
        ),
    ]
